// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjdjvsgykqsuhoksssvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqZGp2c2d5a3FzdWhva3Nzc3ZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNjAzMDksImV4cCI6MjA2NTgzNjMwOX0.I80u9AHV-AzaWDuPvEqMUfqzAQOD0d672xXp5j6qyIU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);